<?php include AkvoWvwParticipantRegistry_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>
<?php
$oForm = $aContent['form'];
?>
<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-pencil"></i>&nbsp;Edit Registrant</h2>
			<a class="btn btn-small" href="<?php echo menu_page_url(\Akvo\WvW\ParticipantRegistry\Admin\Controller\Home::MENU_SLUG, false); ?>"><i class="icon-arrow-left"></i>&nbsp; Back</a>
		</div>
	</div>

	<?php echo $oForm; ?>

	<a class="btn btn-small" href="<?php echo menu_page_url(\Akvo\WvW\ParticipantRegistry\Admin\Controller\Home::MENU_SLUG, false); ?>"><i class="icon-arrow-left"></i>&nbsp; Back</a>

</div>