<?php include AkvoWfwParticipantRegistry_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>

<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-file-text-alt"></i>&nbsp;Registry</h2>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<div id="iDivResponseContainer"></div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span10">

<?php

if (isset($aContent['batches']) && count($aContent['batches']) > 0) {
?>
			<label for="selectBatchFilter">Batch:</label>
			<select id="selectBatchFilter" name="selectBatchFilter">
<?php
	foreach ($aContent['batches'] as $iBatch) {
?>
				<option value="<?php echo $iBatch; ?>"><?php echo $iBatch; ?></option>
<?php
	}
?>
			</select>
<?php
}
?>
		</div>
		<div class="span2">
<?php
if (isset($aContent['registry']) && count($aContent['registry']) > 0) {
?>
			<button class="btn btn-success btn-block btn-large" id="iButtonDownloadList" data-batch="<?php echo $aContent['page-config']['batch']; ?>"><i class="icon icon-download"></i>&nbsp;Download List</button>
<?php
}
?>
		</div>
	</div>
	<div class="row-fluid">
<?php
if (isset($aContent['registry']) && count($aContent['registry']) > 0) {
?>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
                    <?php
                    $dir = ($sOrderByColumn=='country' && $sOrderByDirection=='ASC') ? 'DESC' : 'ASC';
                    ?>
					<th><a href="?page=AWPR_home&order_by_column=country&order_by_direction=<?php echo $dir;?>">Country, School</a></th>
					<?php
                    $dir = ($sOrderByColumn=='support_point' && $sOrderByDirection=='ASC') ? 'DESC' : 'ASC';
                    ?>
					<th><a href="?page=AWPR_home&order_by_column=support_point&order_by_direction=<?php echo $dir;?>">Support point</a></th>
					
					<?php
                    $dir = ($sOrderByColumn=='total_students' && $sOrderByDirection=='ASC') ? 'DESC' : 'ASC';
                    ?>
					<th><a href="?page=AWPR_home&order_by_column=total_students&order_by_direction=<?php echo $dir;?>"># of students</a></th>
					
					<?php
                    $dir = ($sOrderByColumn=='date_of_walk' && $sOrderByDirection=='ASC') ? 'DESC' : 'ASC';
                    ?>
					<th><a href="?page=AWPR_home&order_by_column=date_of_walk&order_by_direction=<?php echo $dir;?>">Walk</a></th>
					
<!--					<th>City, School</th>
					<th>Contact Person, Email</th>
					<th># of Students</th>
					<th>Walk</th>-->
					<th><a class="btn btn-primary btn-small" href="<?php echo menu_page_url(\Akvo\WfW\ParticipantRegistry\Admin\Controller\Home::MENU_SLUG, false); ?>"><i class="icon icon-refresh"></i>&nbsp; Reload</a></th>
				</tr>
			</thead>
			<tbody>
<?php
	foreach ($aContent['registry'] as $mKey => $aRegistryEntry) {

?>
				<tr>
					<td>
						<small><strong><?php echo $aRegistryEntry['country']; ?></strong></small><br>
						<?php echo $aRegistryEntry['name']; ?>
					</td>
					<td><?php echo $aRegistryEntry['support_point']; ?>
						</td>
					<td><?php echo $aRegistryEntry['total_students']; ?></td>
					<td>
						<strong><?php echo $aRegistryEntry['city_of_walk']; ?></strong> on <?php echo date('Y-m-d', strtotime($aRegistryEntry['date_of_walk'])); ?>
					</td>
					<td>
						<div class="btn-group">
							<a class="btn btn-info btn-small" href="<?php echo menu_page_url(\Akvo\WfW\ParticipantRegistry\Admin\Controller\Registrant\Detail::MENU_SLUG, false) . '&id=' . $aRegistryEntry['id']; ?>"><i class="icon-file-text"></i>&nbsp; View</a>
							<a class="btn btn-warning btn-small" href="<?php echo menu_page_url(\Akvo\WfW\ParticipantRegistry\Admin\Controller\Registrant\Edit::MENU_SLUG, false) . '&id=' . $aRegistryEntry['id']; ?>"><i class="icon-pencil"></i>&nbsp; Edit</a>
							<a class="btn btn-danger btn-small" href="<?php echo menu_page_url(\Akvo\WfW\ParticipantRegistry\Admin\Controller\Registrant\Remove::MENU_SLUG, false) . '&id=' . $aRegistryEntry['id']; ?>"><i class="icon-trash"></i>&nbsp; Remove</a>
						</div>
					</td>
				</tr>
<?php

	}
?>
			</tbody>
		</table>
<?php
} else {
?>
		<div class="span12">
			 <div class="alert alert-block alert-error">There are no registered participants for the current batch.</div>
		</div>
<?php
}
?>
	</div>

	<div class="modal hide fade" id="iDivModalDownloadList">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h3>Download List</h3>
		</div>
		<div class="modal-body">
			<p>One fine body…</p>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal">Close</button>
		</div>
	</div>

</div>
