<?php include AkvoWfwParticipantRegistry_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>
<?php
$aDetail = $aContent['detail'];
?>
<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-file-text"></i>&nbsp;Registrant Detail</h2>
			<a class="btn btn-small" href="<?php echo menu_page_url(\Akvo\WfW\ParticipantRegistry\Admin\Controller\Home::MENU_SLUG, false); ?>"><i class="icon-arrow-left"></i>&nbsp; Back</a>
			<a class="btn btn-warning btn-small" href="<?php echo menu_page_url(\Akvo\WfW\ParticipantRegistry\Admin\Controller\Registrant\Edit::MENU_SLUG, false) . '&id=' . $aDetail['id']; ?>"><i class="icon-pencil"></i>&nbsp; Edit</a>
			<a class="btn btn-danger btn-small" href="<?php echo menu_page_url(\Akvo\WfW\ParticipantRegistry\Admin\Controller\Registrant\Remove::MENU_SLUG, false) . '&id=' . $aDetail['id']; ?>"><i class="icon-trash"></i>&nbsp; Remove</a>
		</div>
	</div>

	<div id="iDivRegistrantDetailContainer">
		<div class="row-fluid">
			<div class="span6">
				<div class="row-fluid">
					<div class="span9 offset3">
						<h3>School</h3>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						ID
					</div>
					<div class="span9">
						<?php echo $aDetail['id']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						School Name
					</div>
					<div class="span9">
						<?php echo $aDetail['name']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Address line 1
					</div>
					<div class="span9">
						<?php echo $aDetail['address1']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Address line 2
					</div>
					<div class="span9">
						<?php echo $aDetail['address2']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Address line 3
					</div>
					<div class="span9">
						<?php echo $aDetail['address3']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Country
					</div>
					<div class="span9">
						<?php echo $aDetail['country']; ?>
					</div>
				</div>
				
			</div>
			<div class="span6">
				<div class="row-fluid">
					<div class="span9 offset3">
						<h3>Contact Person</h3>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Name
					</div>
					<div class="span9">
						<?php echo $aDetail['contact_name']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Email
					</div>
					<div class="span9">
						<?php echo $aDetail['email']; ?>
					</div>
				</div>
				
			</div>
		</div>
		<!--<hr>-->
		<div class="row-fluid">
			<div class="span6">
				<div class="row-fluid">
					<div class="span9 offset3">
						<h3>Participation</h3>
					</div>
				</div>
				
				<div class="row-fluid">
					<div class="span3 text-right">
						Total number of students
					</div>
					<div class="span9">
						<?php echo $aDetail['total_students']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Total number of schools
					</div>
					<div class="span9">
						<?php echo $aDetail['total_schools']; ?>
					</div>
				</div>
			</div>
			<div class="span6">
				<div class="row-fluid">
					<div class="span9 offset3">
						<h3>Walk</h3>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Support Point
					</div>
					<div class="span9">
						<?php echo $aDetail['support_point']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Date
					</div>
					<div class="span9">
						<?php echo date('Y-m-d', strtotime($aDetail['date_of_walk'])); ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Project
					</div>
					<div class="span9">
						<?php echo $aDetail['project']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Comments
					</div>
					<div class="span9">
						<?php echo $aDetail['comments']; ?>
					</div>
				</div>

			</div>
		</div>
		<!--<hr>-->
		<div class="row-fluid">
			<div class="span6">
				<div class="row-fluid">
					<div class="span9 offset3">
						<h3>Other/Administrative</h3>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Batch
					</div>
					<div class="span9">
						<?php echo $aDetail['batch']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Date Registered
					</div>
					<div class="span9">
						<?php echo date('Y-m-d', strtotime($aDetail['date_created'])); ?>
					</div>
				</div>
<?php if ($aDetail['date_created'] != $aDetail['date_updated']) {
?>
				<div class="row-fluid">
					<div class="span3 text-right">
						Date Updated
					</div>
					<div class="span9">
						<?php echo date('Y-m-d', strtotime($aDetail['date_updated'])); ?>
					</div>
				</div>
<?php
}
?>
			</div>
			<div class="span6">
				<div class="row-fluid">
					<div class="span9 offset3">
						<h3>Map Placement</h3>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Latitude
					</div>
					<div class="span9">
						<?php echo $aDetail['latitude']; ?>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3 text-right">
						Longitude
					</div>
					<div class="span9">
						<?php echo $aDetail['longitude']; ?>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>