<?php include AkvoWfwParticipantRegistry_Plugin_Dir . '/src/Admin/View/scripts/partials/header.phtml'; ?>

<div class="container-fluid cAWPRContentWrapper">

	<div class="row-fluid">
		<div class="span12">
			<h2><i class="icon-file-text-alt"></i>&nbsp;Support points</h2>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<div id="iDivResponseContainer">
                <?php if(isset($aContent['redirect'])){?>
                <div class="alert alert-success">
                    <h2><i class="icon-ok-sign"></i>&nbsp;Redirecting...</h2>
                    <p>Support point successfully added. You will be redirected to the Supportpoint List in 3 seconds.</p>
                </div>
                <?php } ?>
            </div>
		</div>
		<div class="span6">
            <form name="add_support_point" method="post">
                <div class="control-group">
                    <label class="control-label" for="supportpoint_name">Add new support point:</label>
                    <div class="controls">
                      <input type="text" name="supportpoint_name" id="supportpoint_name" placeholder="Name..." />
                    </div>
                  </div>
                <div class="control-group">
                    <div class="controls">
                      <button type="submit" class="btn" name="support_point_submit" value="submit">submit</button>
                    </div>
                  </div>
                
            </form>
		</div>
	</div>

	
	<div class="row-fluid">
<?php
if (isset($aContent['supportpoints']) && count($aContent['supportpoints']) > 0) {
?>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
                    
					<th>Name</th>
					
					<th><a class="btn btn-primary btn-small" href="<?php echo menu_page_url(\Akvo\WvW\ParticipantRegistry\Admin\Controller\Supportpoint::MENU_SLUG, false); ?>"><i class="icon icon-refresh"></i>&nbsp; Reload</a></th>
				</tr>
			</thead>
			<tbody>
<?php
	foreach ($aContent['supportpoints'] as $mKey => $aSupportpoint) {

?>
				<tr>
					<td>
						<?php echo $aSupportpoint['name']; ?>
					</td>
					
					<td>
						
					</td>
				</tr>
<?php

	}
?>
			</tbody>
		</table>
<?php
} else {
?>
		<div class="span12">
			 <div class="alert alert-block alert-error">There are no support points.</div>
		</div>
<?php
}
?>
	</div>

	

</div>
